<a href="https://colab.research.google.com/github/IqraMuzaffar/Ml_labs/blob/main/linear_regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing libraries**

In [1]:
!pip install numpy

In [ ]:
!pip install scikit-learn

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing

**Creating our dataset**

columns =>   income, age, owner of house, credit rating , decision

In [4]:
dataset=np.array([['Low','Young','FALSE','FALSE','Fair',0],
                    ['Mid','Young','FALSE','FALSE','Good',0],
                    ['High','Young','TRUE','FALSE','Good',1],
                    ['Mid','Young','TRUE','TRUE','Fair',1],
                    ['Mid','Young','FALSE','FALSE','Fair',0],
                    ['Low','Middle','FALSE','FALSE','Fair',0],
                    ['Low','Middle','FALSE','FALSE','Good',0],
                    ['Mid','Middle','TRUE','TRUE','Good',1],
                    ['Mid','Middle','FALSE','TRUE','Excellent',1],
                    ['Mid','Middle','FALSE','TRUE','Excellent',1],
                    ['High','Old','FALSE','TRUE','Excellent',1],
                    ['High','Old','FALSE','TRUE','Good',1],
                    ['High','Old','TRUE','FALSE','Good',1],
                    ['Mid','Old','TRUE','FALSE','Excellent',1],
                    ['Low','Old','FALSE','FALSE','Fair',0]])

**Feature Extraction**

In [5]:
features=dataset[:,0:-1]

print(features)
target=dataset[:,-1]
print(target)

[['Low' 'Young' 'FALSE' 'FALSE' 'Fair']
 ['Mid' 'Young' 'FALSE' 'FALSE' 'Good']
 ['High' 'Young' 'TRUE' 'FALSE' 'Good']
 ['Mid' 'Young' 'TRUE' 'TRUE' 'Fair']
 ['Mid' 'Young' 'FALSE' 'FALSE' 'Fair']
 ['Low' 'Middle' 'FALSE' 'FALSE' 'Fair']
 ['Low' 'Middle' 'FALSE' 'FALSE' 'Good']
 ['Mid' 'Middle' 'TRUE' 'TRUE' 'Good']
 ['Mid' 'Middle' 'FALSE' 'TRUE' 'Excellent']
 ['Mid' 'Middle' 'FALSE' 'TRUE' 'Excellent']
 ['High' 'Old' 'FALSE' 'TRUE' 'Excellent']
 ['High' 'Old' 'FALSE' 'TRUE' 'Good']
 ['High' 'Old' 'TRUE' 'FALSE' 'Good']
 ['Mid' 'Old' 'TRUE' 'FALSE' 'Excellent']
 ['Low' 'Old' 'FALSE' 'FALSE' 'Fair']]
['0' '0' '1' '1' '0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '0']


**Preprocessing**

`preprocessing.OrdinalEncoder()`=> converts categorial data into nominal or numerical data

In [6]:
enc=preprocessing.OrdinalEncoder()
enc.fit(features)
features=enc.transform(features)
print(features)


[[1. 2. 0. 0. 1.]
 [2. 2. 0. 0. 2.]
 [0. 2. 1. 0. 2.]
 [2. 2. 1. 1. 1.]
 [2. 2. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 2.]
 [2. 0. 1. 1. 2.]
 [2. 0. 0. 1. 0.]
 [2. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 2.]
 [0. 1. 1. 0. 2.]
 [2. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1.]]


**Model**

In [7]:
model = LinearRegression()
trained=model.fit(features,target)


**Testing**

In [8]:
#scenario 1
question=np.array([['High','Old','FALSE','FALSE',"Good"]]) #enc.trabsform -> numerical
prediction=trained.predict(enc.transform(question))
print(prediction)
print('2020-CE-45')

[0.20880404]
2020-CE-45


In [9]:
#scenario 2

question=np.array([['High','Old','TRUE','TRUE',"Fair"]]) #enc.trabsform -> numerical
prediction=trained.predict(enc.transform(question))
print(prediction)
print('2020-CE-45')

[1.64996738]
2020-CE-45


In [10]:
#scenario 3

question=np.array([['Low','Middle','FALSE','FALSE',"Good"]]) #enc.trabsform -> numerical
prediction=trained.predict(enc.transform(question))
print(prediction)
print('2020-CE-45')

[0.0616008]
2020-CE-45
