<a href="https://colab.research.google.com/github/IqraMuzaffar/Ml_labs/blob/main/logistic_regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**` Ml_lab(Logistic Regression)`**
 week5

**Importing libraries**

In [ ]:
!pip install numpy

In [ ]:
!pip install scikit-learn

In [2]:
import numpy as np
from sklearn.linear_model import Perceptron, LogisticRegression
from sklearn import preprocessing

**Creating our dataset**

columns =>   income, age, owner of house, credit rating , decision

In [3]:
dataset=np.array([['Low','Young','FALSE','FALSE','Fair','No'],
                    ['Mid','Young','FALSE','FALSE','Good','No'],
                    ['High','Young','TRUE','FALSE','Good','Yes'],
                    ['Mid','Young','TRUE','TRUE','Fair','Yes'],
                    ['Mid','Young','FALSE','FALSE','Fair','No'],
                    ['Low','Middle','FALSE','FALSE','Fair','No'],
                    ['Low','Middle','FALSE','FALSE','Good','No'],
                    ['Mid','Middle','TRUE','TRUE','Good','Yes'],
                    ['Mid','Middle','FALSE','TRUE','Excellent','Yes'],
                    ['Mid','Middle','FALSE','TRUE','Excellent','Yes'],
                    ['High','Old','FALSE','TRUE','Excellent','Yes'],
                    ['High','Old','FALSE','TRUE','Good','Yes'],
                    ['High','Old','TRUE','FALSE','Good','Yes'],
                    ['Mid','Old','TRUE','FALSE','Excellent','Yes'],
                    ['Low','Old','FALSE','FALSE','Fair','No']])

**Feature Extraction**

In [4]:
features=dataset[:,0:-1]

print(features)
target=dataset[:,-1]
print(target)

[['Low' 'Young' 'FALSE' 'FALSE' 'Fair']
 ['Mid' 'Young' 'FALSE' 'FALSE' 'Good']
 ['High' 'Young' 'TRUE' 'FALSE' 'Good']
 ['Mid' 'Young' 'TRUE' 'TRUE' 'Fair']
 ['Mid' 'Young' 'FALSE' 'FALSE' 'Fair']
 ['Low' 'Middle' 'FALSE' 'FALSE' 'Fair']
 ['Low' 'Middle' 'FALSE' 'FALSE' 'Good']
 ['Mid' 'Middle' 'TRUE' 'TRUE' 'Good']
 ['Mid' 'Middle' 'FALSE' 'TRUE' 'Excellent']
 ['Mid' 'Middle' 'FALSE' 'TRUE' 'Excellent']
 ['High' 'Old' 'FALSE' 'TRUE' 'Excellent']
 ['High' 'Old' 'FALSE' 'TRUE' 'Good']
 ['High' 'Old' 'TRUE' 'FALSE' 'Good']
 ['Mid' 'Old' 'TRUE' 'FALSE' 'Excellent']
 ['Low' 'Old' 'FALSE' 'FALSE' 'Fair']]
['No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No']


**Preprocessing**

`preprocessing.OrdinalEncoder()`=> converts categorial data into nominal or numerical data

In [5]:
enc=preprocessing.OrdinalEncoder()
enc.fit(features)
features=enc.transform(features)
print(features)


[[1. 2. 0. 0. 1.]
 [2. 2. 0. 0. 2.]
 [0. 2. 1. 0. 2.]
 [2. 2. 1. 1. 1.]
 [2. 2. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 2.]
 [2. 0. 1. 1. 2.]
 [2. 0. 0. 1. 0.]
 [2. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 2.]
 [0. 1. 1. 0. 2.]
 [2. 1. 1. 0. 0.]
 [1. 1. 0. 0. 1.]]


**Model**

In [6]:
model = LogisticRegression()
trained=model.fit(features,target)


**Testing**

In [8]:
#scenario 1
question=np.array([['High','Old','FALSE','FALSE',"Good"]]) #enc.trabsform -> numerical
prediction=trained.predict(enc.transform(question))
print(prediction)
print('2020-CE-45')

['No']
2020-CE-45


In [7]:
#scenario 2

question=np.array([['High','Old','TRUE','TRUE',"Fair"]]) #enc.trabsform -> numerical
prediction=trained.predict(enc.transform(question))
print(prediction)
print('2020-CE-45')

['Yes']
2020-CE-45


In [9]:
#scenario 3

question=np.array([['Low','Middle','FALSE','FALSE',"Good"]]) #enc.trabsform -> numerical
prediction=trained.predict(enc.transform(question))
print(prediction)
print('2020-CE-45')

['No']
2020-CE-45
